### ISSUE TITLE
Placement and trigger with typescript

### ISSUE THREAD

**Issue by 1ncredibleM1nd** [kseniya57/react-popover#5]
Hi, i use this library, installed @types and library and tried send props like:

` <Popover content={<h1>Kek</h1>} placement="leftTop" trigger="click"></Popover>`

But i have red underlining in placement and trigger with message: 
Type '"leftTop"' is not assignable to type 'PopoverPlacement | undefined'.

**Comment by kseniya57** [comment]
> Hi, i use this library, installed @types and library and tried send props like:
> 
> ` <Popover content={<h1>Kek</h1>} placement="leftTop" trigger="click"></Popover>`
> 
> But i have red underlining in placement and trigger with message: Type '"leftTop"' is not assignable to type 'PopoverPlacement | undefined'.

Hi! `PopoverPlacement` is enum. It's needed to import and use it.

```js
import { PopoverPlacement } from '@idui/react-popover';

PopoverPlacement.leftTop
```

**Comment by kseniya57** [comment]
@1ncredibleM1nd hi! Can I close the issue?

**Comment by 1ncredibleM1nd** [comment]
> @1ncredibleM1nd hi! Can I close the issue?

Yes, u can. Thanks a lot ! It's works for me
